### ISSUE TITLE
All members muted

### ISSUE THREAD

**Issue by bakapolice** [Nerimity/nerimity-web#108]
**Environment**
Google Chrome 129.0.6668.100 (Linux)
Linux Manjaro KDE Plasma 6 1.5
Galaxy S23, Android 14

**Scenario**
1. Enter voice chat with several members

**Actual result**
All members are muted at my view, I cant hear them, but they can hear me
![Screenshot_20241015_122850_Nerimity](https://github.com/user-attachments/assets/d2208a8d-9c6f-4cbd-8276-7d9e328cdb41)

**Comment by SupertigerDev** [comment]
Make sure you are all on the same Nerimity version. there has been changes made.
v1.61.2 is the latest version, can be checked in settings.

![{83D63CA0-0E03-41CD-BC2C-26246FEB86D4}](https://github.com/user-attachments/assets/2031ad6b-f1f9-437b-a7dd-778d3f5a8df8)

**Comment by SupertigerDev** [comment]
Also make sure everyone has unmuted the mic

**Comment by bakapolice** [comment]
Yes, we are all have the same versions 1.61.2. But the others don't have this issue, only me.
Can it be some kind of problem with my profile maybe?

**Comment by bakapolice** [comment]
Some update, this issue randomly appears on all members after reconnect to voice channel

**Comment by SupertigerDev** [comment]
Released another update, please make sure everyone is on the latest update by reloading the page/app. should be fixed.

**Comment by bakapolice** [comment]
Sorry, but No, it's not fixed
The same issue with the same behavior(
